services:
  - type: web
    name: telegram-protection-bot
    env: node
    plan: free
    buildCommand: npm install && pip3 install --upgrade pip && pip3 install -r requirements.txt --no-cache-dir
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /health
  

